require 'pry'
load "flashcards.rb"
file = 'flashcard_samples.txt'
flashcards = File.read(file)
arr = []
flashcards = flashcards.split(/\n+/)
flashcards.each do |fc|
	arr.push(fc)
end

flashcard_stack = FlashcardStack.new

flashcard1 = Flashcard.new(arr[0], arr[1])
flashcard2 = Flashcard.new(arr[2], arr[3])
flashcard3 = Flashcard.new(arr[4], arr[5])
flashcard4 = Flashcard.new(arr[6], arr[7])
flashcard5 = Flashcard.new(arr[8], arr[9])
flashcard6 = Flashcard.new(arr[10], arr[11])
flashcard7 = Flashcard.new(arr[12], arr[13])
flashcard8 = Flashcard.new(arr[14], arr[15])
flashcard9 = Flashcard.new(arr[16], arr[17])
flashcard10 = Flashcard.new(arr[18], arr[19])
flashcard11 = Flashcard.new(arr[20], arr[21])
flashcard12 = Flashcard.new(arr[22], arr[23])
flashcard13 = Flashcard.new(arr[24], arr[25])
flashcard14 = Flashcard.new(arr[26], arr[27])
flashcard15 = Flashcard.new(arr[28], arr[29])
flashcard16 = Flashcard.new(arr[30], arr[31])
flashcard17 = Flashcard.new(arr[32], arr[33])
flashcard18 = Flashcard.new(arr[34], arr[35])
flashcard19 = Flashcard.new(arr[36], arr[37])
flashcard20 = Flashcard.new(arr[38], arr[39])
flashcard21 = Flashcard.new(arr[40], arr[41])
flashcard22 = Flashcard.new(arr[42], arr[43])
flashcard23 = Flashcard.new(arr[44], arr[45])
flashcard24 = Flashcard.new(arr[46], arr[47])
flashcard25 = Flashcard.new(arr[48], arr[49])
flashcard26 = Flashcard.new(arr[50], arr[51])
flashcard27 = Flashcard.new(arr[52], arr[53])
flashcard28 = Flashcard.new(arr[54], arr[55])
flashcard29 = Flashcard.new(arr[56], arr[57])
flashcard30 = Flashcard.new(arr[58], arr[59])
flashcard31 = Flashcard.new(arr[60], arr[61])
flashcard32 = Flashcard.new(arr[62], arr[63])
flashcard33 = Flashcard.new(arr[64], arr[65])
flashcard34 = Flashcard.new(arr[66], arr[67])
flashcard35 = Flashcard.new(arr[68], arr[69])
flashcard36 = Flashcard.new(arr[70], arr[71])
flashcard37 = Flashcard.new(arr[72], arr[73])
flashcard38 = Flashcard.new(arr[74], arr[75])

flashcard_stack.add_flashcards(flashcard1)
flashcard_stack.add_flashcards(flashcard2)
flashcard_stack.add_flashcards(flashcard3)
flashcard_stack.add_flashcards(flashcard4)
flashcard_stack.add_flashcards(flashcard5)
flashcard_stack.add_flashcards(flashcard6)
flashcard_stack.add_flashcards(flashcard7)
flashcard_stack.add_flashcards(flashcard8)
flashcard_stack.add_flashcards(flashcard9)
flashcard_stack.add_flashcards(flashcard10)
flashcard_stack.add_flashcards(flashcard11)
flashcard_stack.add_flashcards(flashcard12)
flashcard_stack.add_flashcards(flashcard13)
flashcard_stack.add_flashcards(flashcard14)
flashcard_stack.add_flashcards(flashcard15)
flashcard_stack.add_flashcards(flashcard16)
flashcard_stack.add_flashcards(flashcard17)
flashcard_stack.add_flashcards(flashcard18)
flashcard_stack.add_flashcards(flashcard19)
flashcard_stack.add_flashcards(flashcard20)
flashcard_stack.add_flashcards(flashcard21)
flashcard_stack.add_flashcards(flashcard22)
flashcard_stack.add_flashcards(flashcard23)
flashcard_stack.add_flashcards(flashcard24)
flashcard_stack.add_flashcards(flashcard25)
flashcard_stack.add_flashcards(flashcard26)
flashcard_stack.add_flashcards(flashcard27)
flashcard_stack.add_flashcards(flashcard28)
flashcard_stack.add_flashcards(flashcard29)
flashcard_stack.add_flashcards(flashcard30)
flashcard_stack.add_flashcards(flashcard31)
flashcard_stack.add_flashcards(flashcard32)
flashcard_stack.add_flashcards(flashcard33)
flashcard_stack.add_flashcards(flashcard34)
flashcard_stack.add_flashcards(flashcard35)
flashcard_stack.add_flashcards(flashcard36)
flashcard_stack.add_flashcards(flashcard37)
flashcard_stack.add_flashcards(flashcard38)
